version: '3.6'
services:
  ai:
    build: ./ai
    volumes:
      - ./ai:/ai
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    depends_on:
      - mongo
    command: bash main.bash
    
  rabbit:
    image: rabbitmq:management-alpine
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    volumes:
      - ../data/rabbitmq/:/var/lib/rabbitmq/
      - ../logs/rabbitmq/:/var/log/rabbitmq

  mongo:
    image: mongo:4.0.23-xenial 
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - ../data/mongodb/:/data/db
