version: '3.6'
services:
  mongo:
    image: mongo:4.0.23-xenial 
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - ../data/mongodb/:/data/db
