version: "3.6"
services:
  mongo:
    image: mongo:4.0.23-xenial
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - ../data/mongodb/:/data/db

  api:
    build: ../../api/
    ports:
      - 8080:8080
    restart: unless-stopped
    command: ["npm", "run", "start"]
    depends_on:
      - mongo

  ui:
    build: ../../adminui/
    ports:
      - 80:3000
    restart: unless-stopped
    command: ["npm", "run", "start"]
    depends_on:
      - api
