version: "3.3"
services:
  mongo:
    image: mongo:4.0.23-xenial
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - ../data/mongodb/:/data/db

  api:
    build: ../../api/
    ports:
      - 9000:9000
    restart: unless-stopped
    command: ["npm", "run", "start"]
    volumes:
      - ../../api:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mongo

  ui:
    build: ../../tempui/
    ports:
      - 80:80
    restart: unless-stopped
    command: ["npm", "run", "start"]
    volumes:
      - ../../tempui:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - api
