version: '3.6'
services:
  rabbit:
    image: rabbitmq:management-alpine
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    volumes:
      - ../data/rabbitmq/:/var/lib/rabbitmq/
      - ../logs/rabbitmq/:/var/log/rabbitmq
    depends_on:
      - redis

  mongo:
    image: mongo:4.0.23-xenial 
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - ../data/mongodb/:/data/db

  redis:
    image: redis:6.2.1-alpine
    ports:
      - 6379:6379
    restart: unless-stopped
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - ../data/redis:/data

  rediscmdr:
    build: ../rediscmdr-image/
    ports:
      - 16379:16379
    restart: unless-stopped
    command: ["redis-commander", "--redis-host", "redis", "--redis-port ", "6379", "--port", "16379"]
    volumes:
      - ../data/redis:/data
    depends_on:
      - redis
    